title: Certutil Misuse - Decode or Remote File Retrieval
id: rule-002
status: production
description: Detects use of certutil.exe to download or decode malicious files.
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image: C:\Windows\System32\certutil.exe
    CommandLine|contains:
      - "decode"
      - "urlcache"
      - "http"
      - "file"
  condition: selection
level: medium
tags:
  - attack.defense_evasion
  - attack.t1140
  - attack.t1105
  - attack.command_and_control
