title: Suspicious mshta.exe Execution From Web
id: rule-009
status: production
description: Detects mshta.exe being used to execute remote HTA files, often used in phishing and malware campaigns.
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image: C:\Windows\System32\mshta.exe
    CommandLine|contains:
      - "http://"
      - "https://"
      - ".hta"
  condition: selection
level: high
tags:
  - attack.execution
  - attack.t1218.005
  - attack.initial_access
