title: PowerShell Launched from Unusual Parent Process
id: rule-005
status: production
description: Detects PowerShell execution where the parent process is unexpected and likely indicates compromise.
logsource:
  category: process_creation
  product: windows
detection:
  powershell:
    Image|endswith: powershell.exe
  suspicious_parent:
    ParentImage|endswith:
      - winword.exe
      - excel.exe
      - outlook.exe
      - Teams.exe
      - mshta.exe
      - regsvr32.exe
  condition: powershell and suspicious_parent
level: high
tags:
  - attack.execution
  - attack.t1059.001
  - attack.t1204
  - attack.defense_evasion
