title: Suspicious Use of regsvr32 for Script Execution
id: rule-007
status: production
description: Detects abuse of regsvr32.exe to execute remote scripts or bypass application control.
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: regsvr32.exe
    CommandLine|contains:
      - "scrobj.dll"
      - "http"
      - "https"
  condition: selection
level: high
tags:
  - attack.defense_evasion
  - attack.execution
  - attack.t1218.010
