title: Runas Abuse with /savecred and Suspicious Target
id: rule-003
status: production
description: Detects usage of runas.exe with saved credentials to launch PowerShell or other scripting tools.
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image|endswith: runas.exe
    CommandLine|contains:
      - "/savecred"
      - "powershell"
      - "cmd"
      - "wscript"
      - "mshta"
  condition: selection
level: medium
tags:
  - attack.privilege_escalation
  - attack.execution
  - attack.t1055
  - attack.t1059
