title: Suspicious Use of schtasks.exe
id: rule-007
status: production
description: Detects use of schtasks.exe to schedule potentially malicious tasks or persistence mechanisms.
logsource:
  category: process_creation
  product: windows
detection:
  selection:
    Image: C:\Windows\System32\schtasks.exe
    CommandLine|contains:
      - "/create"
      - "/tn"
      - "/tr"
      - "cmd.exe"
      - "powershell.exe"
  condition: selection
level: high
tags:
  - attack.persistence
  - attack.execution
  - attack.t1053.005
